package de.locodoko.partie;

public enum Spielphase {
    KARTEN_AUSTEILEN,
    VORBEHALT_ANSAGE,
    VORBEHALT_AUFLOESUNG,
    ARMUT_TAUSCH,
    STICHPHASE,
    AUSWERTUNG,
    GESAMTSTAND_AKTUALISIEREN
}
