spring.datasource.url=${LOCODOKO_DB_URL:jdbc:postgresql://localhost:5432/locodoko}
spring.datasource.username=${LOCODOKO_DB_USERNAME:locodoko}
spring.datasource.password=${LOCODOKO_DB_PASSWORD:locodoko}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
server.servlet.session.cookie.secure=true
